services:
  mundinet:
    container_name: mundinet
    restart: always
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
